version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"  # Expondo a porta do back-end (Apollo Server)
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:root@db:5432/rangoja
      - JWT_SECRET=supersecretkey 
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rangoja
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expondo a porta do PostgreSQL

volumes:
  db_data:
