export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import Footer from "./components/footer";
import Header from "./components/header";

import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="container px-4 mx-auto font-poppins my-6">
          <Header/>
          <div className="bg-white w-full my-6 p-8 rounded-3xl flex justify-center md:justify-start">
            {children}
          </div>
          <Footer/>
        </div>
      </body>
    </html>
  )
}
